name: PyPi Release

on:
    push:
    pull_request:

# based on https://github.com/pypa/gh-action-pypi-publish
jobs:
  build:
    if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mailsort
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.13"
        miniforge-version: latest
        channels: conda-forge
        conda-remove-defaults: "true"
        environment-file: .ci_support/environment-old.yml
    - name: Update dependencies for release
      shell: bash -l {0}
      run: |
        cp .ci_support/environment-old.yml environment.yml
        python .ci_support/release.py; cat pyproject.toml
        git update-index --assume-unchanged pyproject.toml src/mailsort/_version.py
    - name: Build
      shell: bash -l {0}
      run: hatchling build -t sdist -t wheel
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
